# Generated by Django 5.2.17 on 2026-08-21 22:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import apps.payments.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('donations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('payu', 'PayU')], default='payu', max_length=16)),
                ('method', models.CharField(blank=True, max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='COP', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('pending_review', 'Pending review'), ('expired', 'Expired'), ('refunded', 'Refunded')], default='pending', max_length=16)),
                ('reference_code', models.CharField(default=apps.payments.models._generate_reference_code, max_length=32, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=100)),
                ('redirect_url', models.URLField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('donation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='donations.donation')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_intents', to='commerce.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_event_id', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=32)),
                ('payload_json', models.JSONField(blank=True, default=dict)),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('payment_intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='payments.paymentintent')),
            ],
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('donation__isnull', True), ('order__isnull', False)), models.Q(('donation__isnull', False), ('order__isnull', True)), _connector='OR'), name='payment_intent_targets_order_xor_donation'),
        ),
        migrations.AlterUniqueTogether(
            name='paymentevent',
            unique_together={('payment_intent', 'provider_event_id')},
        ),
    ]
